# Generated by Django 6.0.4 on 2026-04-18 14:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("currency", models.CharField(default="USD", max_length=3)),
                (
                    "method",
                    models.CharField(
                        choices=[("stripe", "Stripe"), ("paypal", "PayPal")],
                        db_index=True,
                        default="stripe",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("refunded", "Refunded"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "stripe_payment_intent_id",
                    models.CharField(blank=True, db_index=True, max_length=255),
                ),
                (
                    "stripe_charge_id",
                    models.CharField(blank=True, db_index=True, max_length=255),
                ),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="orders.order",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["order", "-created_at"],
                        name="payments_pa_order_i_288dd3_idx",
                    ),
                    models.Index(
                        fields=["status", "-created_at"],
                        name="payments_pa_status_21ed42_idx",
                    ),
                    models.Index(
                        fields=["stripe_payment_intent_id"],
                        name="payments_pa_stripe__6fe52c_idx",
                    ),
                    models.Index(
                        fields=["stripe_charge_id"],
                        name="payments_pa_stripe__291df3_idx",
                    ),
                ],
            },
        ),
    ]
