# Generated by Django 6.0.4 on 2026-04-18 14:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="product",
            new_name="products_pr_slug_3edc0c_idx",
            old_name="products_p_slug_idx",
        ),
        migrations.RenameIndex(
            model_name="product",
            new_name="products_pr_categor_50f5f1_idx",
            old_name="products_p_categor_idx",
        ),
        migrations.AlterField(
            model_name="category",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="customizationoption",
            name="display_order",
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name="customizationoption",
            name="name",
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="customizationvalue",
            name="display_order",
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name="customizationvalue",
            name="is_default",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="inventory",
            name="stock_quantity",
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name="product",
            name="base_price",
            field=models.DecimalField(
                db_index=True,
                decimal_places=2,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="is_featured",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(db_index=True, max_length=300),
        ),
        migrations.AlterField(
            model_name="product",
            name="sku",
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="display_order",
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddIndex(
            model_name="category",
            index=models.Index(
                fields=["name", "is_active"], name="products_ca_name_752bb1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customizationoption",
            index=models.Index(
                fields=["name", "option_type"], name="products_cu_name_85f05f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customizationvalue",
            index=models.Index(
                fields=["option", "is_default"], name="products_cu_option__48157d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="inventory",
            index=models.Index(
                fields=["stock_quantity", "low_stock_threshold"],
                name="products_in_stock_q_a65164_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["is_active", "is_featured", "-created_at"],
                name="products_pr_is_acti_ca2c23_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["base_price"], name="products_pr_base_pr_658bee_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["name", "is_active"], name="products_pr_name_59cb5e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productcustomization",
            index=models.Index(
                fields=["product", "option"], name="products_pr_product_335a46_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productimage",
            index=models.Index(
                fields=["product", "display_order"],
                name="products_pr_product_48d699_idx",
            ),
        ),
    ]
